### ISSUE TITLE
Apostrophes in Field Values not escaped

### ISSUE THREAD

**Issue by robinmaisch** [namnoops/merjapp#1]
Merging fails when a field value, in my case a group title, contains an apostrophe (').
I'd suggest escaping all key names inside single quotes, perhaps like so:
```
Merge.java
106    valueList.add("'" + fieldValues[i].toString().replaceAll("'","''") + "'");
```

**Comment by namnoops** [comment]
@robinmaisch could you create a pull request for that?

**Comment by namnoops** [comment]
Hi @robinmaisch, you're totally right. Could you create a PR for that change?
